SportStore/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace SportStore.Models
{
    public class Order
    {
        public int OrderId { get; set; }

        [Required(ErrorMessage = "Please, enter a name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please, enter the first address line")]
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        [Required(ErrorMessage = "Please, enter the city name")]
        public string City { get; set; }
        [Required(ErrorMessage = "Please, enter a state name")]
        public string State { get; set; }
        public string Zip { get; set; }
        [Required(ErrorMessage = "Please, enter a country name")]
        public string Country { get; set; }
        public bool GiftWarp { get; set; }

        [BindNever]
        public bool Snipped { get; set; }

        [BindNever]
        public virtual ICollection<CartLine> Lines { get; set; } = new HashSet<CartLine>();
    }
}

SportStore/Controllers/OrderController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportStore.Models;
using SportStore.Models.Repo;

namespace SportStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository repository;
        private readonly CartBase cartService;

        public OrderController(IOrderRepository repository, CartBase cartService) => (this.repository, this.cartService) = (repository, cartService);

        public IActionResult Index() => RedirectToAction("Index", controllerName: "Cart", new {returnUrl = "/"});

        [HttpGet]
        public IActionResult Checkout() => View(new Order());

        [HttpPost]
        [ActionName("Checkout")]
        public async Task<IActionResult> CheckoutSubmitted(Order order)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (!this.cartService.CartLines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
                return View(order);
            }

            try
            {
                this.cartService.CartLines.ForEach(line => order.Lines.Add(line));
                await this.repository.SaveOrder(order);
            }
            catch (DbUpdateConcurrencyException)
            {
                ModelState.AddModelError("", "An exception occurred during processing your order. Try again or complete order later.");
                return View();
            }
            
            this.cartService.Clear();
            return View("Completed", order.OrderId);
        }
    }
}

SportStore/Controllers/StoreController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;
using SportStore.Models.Repo;
using SportStore.Models.ViewModels;

namespace SportStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly IStoreRepository repository;

        public StoreController(IStoreRepository repository) => this.repository = repository ??
            throw new ArgumentNullException(nameof(repository), "Store repository can't be null");

        public IActionResult Index(string category, int pageIndex = 1)
        {
            const int pageSize = 4;

            Func<Product, bool> predicate = category is null
                ? x => true
                : x => x.Category == category;

            return View(new ProductsListViewModel()
            {
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = pageSize, ItemsPerPage = pageSize,
                    TotalItems = string.IsNullOrEmpty(category)
                        ? repository.Products.Count()
                        : repository.Products.Count(x => x.Category == category)
                },

                Products = repository.Products.Where(predicate)
                    .OrderBy(x => x.ProductId).Skip((pageIndex - 1) * pageSize).Take(pageSize),
                CurrentCategory = category
            });
        }

        public IActionResult Privacy() => View();
    }
}

SportStore/Views/Order/Checkout.cshtml
@model Order

@{
    Layout = "_Layout";
    ViewData["Title"] = "Order page";
}

<h2>Checkout now</h2>
<p>Please enter you details, and we will ship your goods right away!</p>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Order" asp-action="Checkout" method="post">
    <h3>Ship to:</h3>
    <div class="form-control">
        <label asp-for="Name"class="form-label"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <h3>Address:</h3>
    <div class="form-control">
        <label asp-for="Line1" class="form-label"></label>
        <input asp-for="Line1" class="form-control" />
    </div>
    <div>
        <label asp-for="Line2" class="form-label"></label>
        <input asp-for="Line2" class="form-control" />
    </div>
    <div>
        <label asp-for="Line3" class="form-label"></label>
        <input asp-for="Line3" class="form-control" />
    </div>
    <div>
        <label asp-for="City" class="form-label"></label>
        <input asp-for="City" class="form-control" />
    </div>
    <div>
        <label asp-for="State" class="form-label"></label>
        <input asp-for="State" class="form-control" />
    </div>
    <div>
        <label asp-for="Zip" class="form-label"></label>
        <input asp-for="Zip" class="form-control" />
    </div>
    <div>
        <label asp-for="Country" class="form-label"></label>
        <input asp-for="Country" class="form-control" />
    </div>
    <h3>Options:</h3>
    <div class="form-check">
        <label asp-for="GiftWarp" class="form-label"></label>
        <input asp-for="GiftWarp" class="form-control"/>
    </div>
    <div class="text-center">
        <button type="submit" value="Complete Order" class="btn btn-success">Complete Order</button>
    </div>
</form>

SportStore/Views/Order/Completed.cshtml
@model int

@{
    this.Layout = "_CartLayout";
    ViewData["Title"] = "Success!";
}

<div class="text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing order #@Model</p>
    <p>We'll ship your goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Store" asp-action="Index">Return to store</a>
</div>