SportStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;

namespace SportStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly CartBase cart;

        public CartSummaryViewComponent(CartBase cart) => this.cart = cart;

        public IViewComponentResult Invoke() => View(cart);
    }
}

SportStore/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models.Repo;

namespace SportStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IStoreRepository repository;

        public NavigationMenuViewComponent(IStoreRepository repository) => this.repository = repository;

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x));
        }
    }
}

SportStore/Controllers/StoreController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;
using SportStore.Models.Repo;
using SportStore.Models.ViewModels;

namespace SportStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly IStoreRepository repository;

        public StoreController(IStoreRepository repository) => this.repository = repository ??
            throw new ArgumentNullException(nameof(repository), "Store repository can't be null");

        public IActionResult Index(string category, int pageIndex = 1)
        {
            const int pageSize = 4;

            Func<Product, bool> predicate = category is null
                ? x => true
                : x => x.Category == category;

            return View(new ProductsListViewModel()
            {
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = pageSize, ItemsPerPage = pageSize,
                    TotalItems = string.IsNullOrEmpty(category)
                        ? repository.Products.Count()
                        : repository.Products.Count(x => x.Category == category)
                },

                Products = repository.Products.Where(predicate)
                    .OrderBy(x => x.ProductId).Skip((pageIndex - 1) * pageSize).Take(pageSize),
                CurrentCategory = category
            });
        }

        public IActionResult Privacy() => View();
    }
}

SportStore/Views/Shared/ProductSummary.cshtml
@using SportStore.Infrastructure
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Product

<div class="card m-1 p-1">
    <div class="bg-gradient p-1">
        <h4>
            @Model.Name
            <span style="float: right">
                <small>@Model.Price.ToString("C")</small>
            </span>
        </h4>
    </div>
    <input type="hidden" asp-for="ProductId"/>
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
    <span class="card-text p-1">
        @Model.Description
    </span>
    <div class="container">
        <button type="button" onclick="AddToCart(@Model.ProductId)" class="btn btn-success btn-sm" style="float: right">Add</button>
    </div>
</div>

<script>
    function AddToCart(id) {
        var xhttp = new XMLHttpRequest();
        xhttp.onload = function() {
            $('#cartSummary').html(this.response);
        };

        xhttp.open("GET", "/Cart/AddToCart?productId=" + id, true);
        xhttp.send();
    }
</script>

SportStore/Views/Shared/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sport Store Cart</title>
    <link rel="stylesheet" href="lib/twitter-bootstrap/css/bootstrap.min.css"></>
</head>
<body>
<div class="bg-danger text-white p-2">
    <span class="navbar-brand m-2">Sport Store</span>
</div>
<div class="m-1 p-1">
    @RenderBody()
</div>
</body>
</html>

SportStore/Views/Shared/_Layout.cshtml
@using SportStore.Infrastructure
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width", initial-scale="1.0" />
    <title>@ViewBag.Title - Sport Store Application</title>
    <link rel="stylesheet" href="lib/twitter-bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="lib/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Store" asp-action="Index">Sport Store</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <div id="cartSummary">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="row m-1 p-1">
    <div id="categories" class="col-10">
        <vc:navigation-menu></vc:navigation-menu>
    </div>
</div>
<div class="container pb-3">
    <main>
        @RenderBody()
    </main>
</div>
<footer class="border-top modal-footer text-muted">
    <div class="container">
        &copy; 2021 SportStore <a asp-controller="Store" asp-action="Privacy">Privacy</a>
    </div>
    <script src="lib/jquery/jquery.min.js"></script>
    <script src="lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("script", required: false)
</footer>
</body>
</html>